//------------------------------------------------------------------------------
// <auto-generated>
//     Generated for PeekVPN localization.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace PeekVPN.App.Localization;

using System.Globalization;
using System.Resources;

public static class Strings
{
    private static readonly ResourceManager ResourceManager =
        new("PeekVPN.App.Localization.Strings", typeof(Strings).Assembly);

    private static CultureInfo? _culture;

    public static CultureInfo? Culture
    {
        get => _culture;
        set => _culture = value;
    }

    public static string AppTitle => Get(nameof(AppTitle));
    public static string BrandPremium => Get(nameof(BrandPremium));
    public static string SearchServersWatermark => Get(nameof(SearchServersWatermark));

    public static string NavMap => Get(nameof(NavMap));
    public static string NavStatistic => Get(nameof(NavStatistic));
    public static string NavStatistics => Get(nameof(NavStatistics));
    public static string NavProfile => Get(nameof(NavProfile));
    public static string NavSettings => Get(nameof(NavSettings));
    public static string NavSupport => Get(nameof(NavSupport));
    public static string NavLogOut => Get(nameof(NavLogOut));

    public static string UpsellTitle => Get(nameof(UpsellTitle));
    public static string UpsellButton => Get(nameof(UpsellButton));

    public static string MapTitle => Get(nameof(MapTitle));
    public static string ConnectionPanelTitle => Get(nameof(ConnectionPanelTitle));
    public static string StatsSummaryTitle => Get(nameof(StatsSummaryTitle));
    public static string StatsWeeklyConnections => Get(nameof(StatsWeeklyConnections));
    public static string StatsWeeklyConnectionsValue => Get(nameof(StatsWeeklyConnectionsValue));
    public static string StatsPing => Get(nameof(StatsPing));
    public static string StatsSpeed => Get(nameof(StatsSpeed));
    public static string StatsSpeedValue => Get(nameof(StatsSpeedValue));
    public static string StatsPlaceholder => Get(nameof(StatsPlaceholder));
    public static string RecentConnectionsTitle => Get(nameof(RecentConnectionsTitle));
    public static string AllServersTitle => Get(nameof(AllServersTitle));
    public static string EmptyRecent => Get(nameof(EmptyRecent));

    public static string StatusDisconnected => Get(nameof(StatusDisconnected));
    public static string StatusConnecting => Get(nameof(StatusConnecting));
    public static string StatusConnected => Get(nameof(StatusConnected));
    public static string StatusSecured => Get(nameof(StatusSecured));
    public static string StatusNotSecured => Get(nameof(StatusNotSecured));
    public static string StatusPaused => Get(nameof(StatusPaused));
    public static string StatusDisconnecting => Get(nameof(StatusDisconnecting));
    public static string LocationFormat => Get(nameof(LocationFormat));

    public static string HeadlineUnprotected => Get(nameof(HeadlineUnprotected));
    public static string HeadlineConnecting => Get(nameof(HeadlineConnecting));
    public static string HeadlineProtected => Get(nameof(HeadlineProtected));
    public static string HeadlinePaused => Get(nameof(HeadlinePaused));
    public static string HeadlineDisconnecting => Get(nameof(HeadlineDisconnecting));

    public static string BodyUnprotected => Get(nameof(BodyUnprotected));
    public static string BodyConnecting => Get(nameof(BodyConnecting));
    public static string BodyProtected => Get(nameof(BodyProtected));
    public static string BodyPaused => Get(nameof(BodyPaused));
    public static string BodyDisconnecting => Get(nameof(BodyDisconnecting));

    public static string CtaQuickConnect => Get(nameof(CtaQuickConnect));
    public static string CtaDisconnect => Get(nameof(CtaDisconnect));
    public static string CtaResume => Get(nameof(CtaResume));
    public static string CtaPause => Get(nameof(CtaPause));
    public static string CtaCancel => Get(nameof(CtaCancel));
    public static string CtaBusy => Get(nameof(CtaBusy));

    public static string FeatureThreatTitle => Get(nameof(FeatureThreatTitle));
    public static string FeatureThreatBadge => Get(nameof(FeatureThreatBadge));
    public static string FeatureThreatBody => Get(nameof(FeatureThreatBody));

    public static string FeatureDarkWebTitle => Get(nameof(FeatureDarkWebTitle));
    public static string FeatureDarkWebBadge => Get(nameof(FeatureDarkWebBadge));
    public static string FeatureDarkWebBody => Get(nameof(FeatureDarkWebBody));

    public static string FeatureDoubleVpnTitle => Get(nameof(FeatureDoubleVpnTitle));
    public static string FeatureDoubleVpnBadge => Get(nameof(FeatureDoubleVpnBadge));
    public static string FeatureDoubleVpnBody => Get(nameof(FeatureDoubleVpnBody));

    public static string LatencyFormat => Get(nameof(LatencyFormat));
    public static string LoadingServers => Get(nameof(LoadingServers));
    public static string ErrorLoadServers => Get(nameof(ErrorLoadServers));

    public static string StatisticsPageTitle => Get(nameof(StatisticsPageTitle));
    public static string StatisticsPageSubtitle => Get(nameof(StatisticsPageSubtitle));
    public static string StatisticsProtectedTime => Get(nameof(StatisticsProtectedTime));
    public static string StatisticsProtectedTimeValue => Get(nameof(StatisticsProtectedTimeValue));
    public static string StatisticsDataProtected => Get(nameof(StatisticsDataProtected));
    public static string StatisticsDataProtectedValue => Get(nameof(StatisticsDataProtectedValue));
    public static string StatisticsAverageSpeed => Get(nameof(StatisticsAverageSpeed));
    public static string StatisticsAverageSpeedValue => Get(nameof(StatisticsAverageSpeedValue));
    public static string StatisticsConnections => Get(nameof(StatisticsConnections));
    public static string StatisticsConnectionsValue => Get(nameof(StatisticsConnectionsValue));
    public static string StatisticsActivityTitle => Get(nameof(StatisticsActivityTitle));
    public static string StatisticsActivitySubtitle => Get(nameof(StatisticsActivitySubtitle));
    public static string StatisticsDownload => Get(nameof(StatisticsDownload));
    public static string StatisticsUpload => Get(nameof(StatisticsUpload));
    public static string StatisticsLocationsTitle => Get(nameof(StatisticsLocationsTitle));
    public static string StatisticsLocationsSubtitle => Get(nameof(StatisticsLocationsSubtitle));
    public static string StatisticsGermany => Get(nameof(StatisticsGermany));
    public static string StatisticsNetherlands => Get(nameof(StatisticsNetherlands));
    public static string StatisticsUnitedStates => Get(nameof(StatisticsUnitedStates));
    public static string StatisticsToday => Get(nameof(StatisticsToday));
    public static string StatisticsLastSevenDays => Get(nameof(StatisticsLastSevenDays));

    public static string ProfilePageTitle => Get(nameof(ProfilePageTitle));
    public static string ProfilePageSubtitle => Get(nameof(ProfilePageSubtitle));
    public static string ProfileDisplayName => Get(nameof(ProfileDisplayName));
    public static string ProfileEmailAddress => Get(nameof(ProfileEmailAddress));
    public static string ProfilePlanLabel => Get(nameof(ProfilePlanLabel));
    public static string ProfilePlanValue => Get(nameof(ProfilePlanValue));
    public static string ProfileRenewsLabel => Get(nameof(ProfileRenewsLabel));
    public static string ProfileRenewsValue => Get(nameof(ProfileRenewsValue));
    public static string ProfileAccountTitle => Get(nameof(ProfileAccountTitle));
    public static string ProfileAccountSubtitle => Get(nameof(ProfileAccountSubtitle));
    public static string ProfileMemberSinceLabel => Get(nameof(ProfileMemberSinceLabel));
    public static string ProfileMemberSinceValue => Get(nameof(ProfileMemberSinceValue));
    public static string ProfileDevicesLabel => Get(nameof(ProfileDevicesLabel));
    public static string ProfileDevicesValue => Get(nameof(ProfileDevicesValue));
    public static string ProfileProtectionTitle => Get(nameof(ProfileProtectionTitle));
    public static string ProfileProtectionSubtitle => Get(nameof(ProfileProtectionSubtitle));
    public static string ProfileProtectionValue => Get(nameof(ProfileProtectionValue));
    public static string ProfileManagePlan => Get(nameof(ProfileManagePlan));
    public static string ProfileEditProfile => Get(nameof(ProfileEditProfile));

    public static string SettingsVpnConnectionSection => Get(nameof(SettingsVpnConnectionSection));
    public static string SettingsSecurityAndPrivacySection => Get(nameof(SettingsSecurityAndPrivacySection));
    public static string SettingsGeneralSection => Get(nameof(SettingsGeneralSection));
    public static string SettingsAutoConnectTitle => Get(nameof(SettingsAutoConnectTitle));
    public static string SettingsAutoConnectDescription => Get(nameof(SettingsAutoConnectDescription));
    public static string SettingsAutoConnectTargetTitle => Get(nameof(SettingsAutoConnectTargetTitle));
    public static string SettingsAutoConnectTargetDescription => Get(nameof(SettingsAutoConnectTargetDescription));
    public static string SettingsFastestServer => Get(nameof(SettingsFastestServer));
    public static string SettingsAutoConnectServerTitle => Get(nameof(SettingsAutoConnectServerTitle));
    public static string SettingsAutoConnectServerDescription => Get(nameof(SettingsAutoConnectServerDescription));
    public static string SettingsServerPlaceholder => Get(nameof(SettingsServerPlaceholder));
    public static string SettingsServerAmsterdam => Get(nameof(SettingsServerAmsterdam));
    public static string SettingsServerNewYork => Get(nameof(SettingsServerNewYork));
    public static string SettingsServerSingapore => Get(nameof(SettingsServerSingapore));
    public static string SettingsSplitTunnelingTitle => Get(nameof(SettingsSplitTunnelingTitle));
    public static string SettingsSplitTunnelingDescription => Get(nameof(SettingsSplitTunnelingDescription));
    public static string SettingsSplitTunnelingDomainsTitle => Get(nameof(SettingsSplitTunnelingDomainsTitle));
    public static string SettingsSplitTunnelingDomainsDescription => Get(nameof(SettingsSplitTunnelingDomainsDescription));
    public static string SettingsSplitTunnelingApplicationsTitle => Get(nameof(SettingsSplitTunnelingApplicationsTitle));
    public static string SettingsSplitTunnelingApplicationsDescription => Get(nameof(SettingsSplitTunnelingApplicationsDescription));
    public static string SettingsSplitTunnelingAddDomainWatermark => Get(nameof(SettingsSplitTunnelingAddDomainWatermark));
    public static string SettingsSplitTunnelingAddApplicationWatermark => Get(nameof(SettingsSplitTunnelingAddApplicationWatermark));
    public static string SettingsSplitTunnelingAddButton => Get(nameof(SettingsSplitTunnelingAddButton));
    public static string SettingsSplitTunnelingDomainsEmpty => Get(nameof(SettingsSplitTunnelingDomainsEmpty));
    public static string SettingsSplitTunnelingApplicationsEmpty => Get(nameof(SettingsSplitTunnelingApplicationsEmpty));
    public static string SettingsKillSwitchTitle => Get(nameof(SettingsKillSwitchTitle));
    public static string SettingsKillSwitchDescription => Get(nameof(SettingsKillSwitchDescription));
    public static string SettingsKillSwitchModeTitle => Get(nameof(SettingsKillSwitchModeTitle));
    public static string SettingsKillSwitchModeDescription => Get(nameof(SettingsKillSwitchModeDescription));
    public static string SettingsKillSwitchSoftMode => Get(nameof(SettingsKillSwitchSoftMode));
    public static string SettingsKillSwitchHardMode => Get(nameof(SettingsKillSwitchHardMode));
    public static string SettingsVpnProtocolTitle => Get(nameof(SettingsVpnProtocolTitle));
    public static string SettingsVpnProtocolDescription => Get(nameof(SettingsVpnProtocolDescription));
    public static string SettingsProtocolRecommended => Get(nameof(SettingsProtocolRecommended));
    public static string SettingsProtocolOpenVpn => Get(nameof(SettingsProtocolOpenVpn));
    public static string SettingsProtocolIkev2 => Get(nameof(SettingsProtocolIkev2));
    public static string SettingsCustomDnsTitle => Get(nameof(SettingsCustomDnsTitle));
    public static string SettingsCustomDnsDescription => Get(nameof(SettingsCustomDnsDescription));
    public static string SettingsAutoStartupTitle => Get(nameof(SettingsAutoStartupTitle));
    public static string SettingsAutoStartupDescription => Get(nameof(SettingsAutoStartupDescription));
    public static string SettingsStayHiddenTitle => Get(nameof(SettingsStayHiddenTitle));
    public static string SettingsStayHiddenDescription => Get(nameof(SettingsStayHiddenDescription));
    public static string SettingsAutoUpdatesTitle => Get(nameof(SettingsAutoUpdatesTitle));
    public static string SettingsAutoUpdatesDescription => Get(nameof(SettingsAutoUpdatesDescription));
    public static string SettingsAllowBackgroundProcessesTitle => Get(nameof(SettingsAllowBackgroundProcessesTitle));
    public static string SettingsAllowBackgroundProcessesDescription => Get(nameof(SettingsAllowBackgroundProcessesDescription));
    public static string SettingsAppearanceTitle => Get(nameof(SettingsAppearanceTitle));
    public static string SettingsAppearanceDescription => Get(nameof(SettingsAppearanceDescription));
    public static string SettingsAppearanceSystem => Get(nameof(SettingsAppearanceSystem));
    public static string SettingsAppearanceLight => Get(nameof(SettingsAppearanceLight));
    public static string SettingsAppearanceDark => Get(nameof(SettingsAppearanceDark));
    public static string SettingsShowNotificationsTitle => Get(nameof(SettingsShowNotificationsTitle));
    public static string SettingsShowNotificationsDescription => Get(nameof(SettingsShowNotificationsDescription));
    public static string SettingsSendAppLogsTitle => Get(nameof(SettingsSendAppLogsTitle));
    public static string SettingsSendAppLogsDescription => Get(nameof(SettingsSendAppLogsDescription));
    public static string SettingsResetSettingsTitle => Get(nameof(SettingsResetSettingsTitle));
    public static string SettingsResetSettingsDescription => Get(nameof(SettingsResetSettingsDescription));
    public static string SettingsResetSettingsButton => Get(nameof(SettingsResetSettingsButton));
    private static string Get(string name)
        => ResourceManager.GetString(name, _culture) ?? name;
}
