//------------------------------------------------------------------------------
// <auto-generated>
//     Generated for PeekVPN localization.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace PeekVPN.App.Localization;

using System.Globalization;
using System.Resources;

public static class Strings
{
    private static readonly ResourceManager ResourceManager =
        new("PeekVPN.App.Localization.Strings", typeof(Strings).Assembly);

    private static CultureInfo? _culture;

    public static CultureInfo? Culture
    {
        get => _culture;
        set => _culture = value;
    }

    public static string AppTitle => Get(nameof(AppTitle));
    public static string BrandPremium => Get(nameof(BrandPremium));
    public static string SearchServersWatermark => Get(nameof(SearchServersWatermark));

    public static string NavMap => Get(nameof(NavMap));
    public static string NavStatistic => Get(nameof(NavStatistic));
    public static string NavProfile => Get(nameof(NavProfile));
    public static string NavSettings => Get(nameof(NavSettings));
    public static string NavSupport => Get(nameof(NavSupport));
    public static string NavLogOut => Get(nameof(NavLogOut));

    public static string UpsellTitle => Get(nameof(UpsellTitle));
    public static string UpsellButton => Get(nameof(UpsellButton));

    public static string MapTitle => Get(nameof(MapTitle));
    public static string ConnectionPanelTitle => Get(nameof(ConnectionPanelTitle));
    public static string StatsSummaryTitle => Get(nameof(StatsSummaryTitle));
    public static string StatsWeeklyConnections => Get(nameof(StatsWeeklyConnections));
    public static string StatsWeeklyConnectionsValue => Get(nameof(StatsWeeklyConnectionsValue));
    public static string StatsPing => Get(nameof(StatsPing));
    public static string StatsSpeed => Get(nameof(StatsSpeed));
    public static string StatsSpeedValue => Get(nameof(StatsSpeedValue));
    public static string StatsPlaceholder => Get(nameof(StatsPlaceholder));
    public static string RecentConnectionsTitle => Get(nameof(RecentConnectionsTitle));
    public static string AllServersTitle => Get(nameof(AllServersTitle));
    public static string EmptyRecent => Get(nameof(EmptyRecent));

    public static string StatusDisconnected => Get(nameof(StatusDisconnected));
    public static string StatusConnecting => Get(nameof(StatusConnecting));
    public static string StatusConnected => Get(nameof(StatusConnected));
    public static string StatusSecured => Get(nameof(StatusSecured));
    public static string StatusNotSecured => Get(nameof(StatusNotSecured));
    public static string StatusPaused => Get(nameof(StatusPaused));
    public static string StatusDisconnecting => Get(nameof(StatusDisconnecting));
    public static string LocationFormat => Get(nameof(LocationFormat));

    public static string HeadlineUnprotected => Get(nameof(HeadlineUnprotected));
    public static string HeadlineConnecting => Get(nameof(HeadlineConnecting));
    public static string HeadlineProtected => Get(nameof(HeadlineProtected));
    public static string HeadlinePaused => Get(nameof(HeadlinePaused));
    public static string HeadlineDisconnecting => Get(nameof(HeadlineDisconnecting));

    public static string BodyUnprotected => Get(nameof(BodyUnprotected));
    public static string BodyConnecting => Get(nameof(BodyConnecting));
    public static string BodyProtected => Get(nameof(BodyProtected));
    public static string BodyPaused => Get(nameof(BodyPaused));
    public static string BodyDisconnecting => Get(nameof(BodyDisconnecting));

    public static string CtaQuickConnect => Get(nameof(CtaQuickConnect));
    public static string CtaDisconnect => Get(nameof(CtaDisconnect));
    public static string CtaResume => Get(nameof(CtaResume));
    public static string CtaPause => Get(nameof(CtaPause));
    public static string CtaCancel => Get(nameof(CtaCancel));
    public static string CtaBusy => Get(nameof(CtaBusy));

    public static string FeatureThreatTitle => Get(nameof(FeatureThreatTitle));
    public static string FeatureThreatBadge => Get(nameof(FeatureThreatBadge));
    public static string FeatureThreatBody => Get(nameof(FeatureThreatBody));

    public static string FeatureDarkWebTitle => Get(nameof(FeatureDarkWebTitle));
    public static string FeatureDarkWebBadge => Get(nameof(FeatureDarkWebBadge));
    public static string FeatureDarkWebBody => Get(nameof(FeatureDarkWebBody));

    public static string FeatureDoubleVpnTitle => Get(nameof(FeatureDoubleVpnTitle));
    public static string FeatureDoubleVpnBadge => Get(nameof(FeatureDoubleVpnBadge));
    public static string FeatureDoubleVpnBody => Get(nameof(FeatureDoubleVpnBody));

    public static string LatencyFormat => Get(nameof(LatencyFormat));
    public static string LoadingServers => Get(nameof(LoadingServers));
    public static string ErrorLoadServers => Get(nameof(ErrorLoadServers));

    private static string Get(string name)
        => ResourceManager.GetString(name, _culture) ?? name;
}
