<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PeekVPN.Contracts\PeekVPN.Contracts.csproj" />
    <ProjectReference Include="..\PeekVPN.Core\PeekVPN.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="Grpc.Net.Client" Version="2.76.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PeekVPN.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Native\win-x64\wintun.dll" Condition="Exists('Native\win-x64\wintun.dll')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <TargetPath>wintun.dll</TargetPath>
    </None>
    <None Include="Native\win-x64\wintun-LICENSE.txt" Condition="Exists('Native\win-x64\wintun-LICENSE.txt')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <TargetPath>wintun-LICENSE.txt</TargetPath>
    </None>
  </ItemGroup>

  <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
